name = "CuNESSie"
uuid = "0d043cba-454f-40cc-8503-cb153d0e1409"
desc = "CUDA-accelerated Nonlocal Electrostatics in Structured Solvents"
version = "0.4.0"
authors = ["Thomas Kemmer <thomas@binaryden.de>"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NESSie = "f00e83c4-bd01-11e9-272c-ff1b96fb444d"
Preconditioners = "af69fa37-3177-5a40-98ee-561f696e4fcd"

[compat]
Adapt = "4"
Aqua = "0.8.14"
CUDA = "5.8"
IterativeSolvers = "0.8, 0.9"
LinearAlgebra = "1.10"
NESSie = "1.4"
ParallelTestRunner = "2.0.1"
Preconditioners = "0.6"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ParallelTestRunner = "d3525ed8-44d0-4b2c-a655-542cee43accc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ParallelTestRunner", "Test"]
