name = "CuNESSie"
uuid = "0d043cba-454f-40cc-8503-cb153d0e1409"
desc = "CUDA-accelerated Nonlocal Electrostatics in Structured Solvents"
authors = ["Thomas Kemmer <thomas@binaryden.de>"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDAnative = "be33ccc6-a3ff-5ff2-a52e-74243cff1e17"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NESSie = "f00e83c4-bd01-11e9-272c-ff1b96fb444d"
Preconditioners = "af69fa37-3177-5a40-98ee-561f696e4fcd"

[compat]
julia = "1"
Adapt = "1, 2"
CUDAnative = "2.9, 3"
CuArrays = "1.7, 2"
ImplicitArrays = "0.2"
IterativeSolvers = "0.8"
NESSie = "1.1"
Preconditioners = "0.3"

[extras]
ImplicitArrays = "2c62951c-9479-4435-88c8-614a84373d38"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ImplicitArrays", "Test"]
